apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: theme-toolkit
  description: Functions of theme
  tags:
    - javascript
spec:
  type: library
  owner: digitals
  lifecycle: production
