name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  call-workflow:
    uses: platformbuilders/actions-workflows/.github/workflows/check-react-lib.yml@fix/checkLib
    secrets:
      SONAR_TOKEN: "123123123"
